import { getOperation } from '../operations/registry';
import { operandAt } from '../range';
import type { Problem } from '../types';

/**
 * The two numbers of the underlying fact. For an operation generated by inverting another
 * (subtraction, division), the shown operands are [a op b, a] and the answer is b, so the
 * fact is [a, b]. 14 – 7 is the fact 7 + 7, and 56 ÷ 7 is the fact 7 × 8.
 */
export function factPair(problem: Problem): readonly [number, number] {
  const op = getOperation(problem.opId);
  if (op.derivesFrom !== undefined) return [operandAt(problem.operands, 1), problem.answer];
  return [operandAt(problem.operands, 0), operandAt(problem.operands, 1)];
}

/** The operation a problem's fact belongs to: 'add' for subtraction, 'mul' for division. */
export function baseOpId(problem: Problem): string {
  return getOperation(problem.opId).derivesFrom ?? problem.opId;
}

export function digitsOf(n: number): string {
  return String(n);
}
