import type { GeneratorParams, Problem, Range, Rng } from '../types';

export interface RangeSpec {
  /** Key into GeneratorParams.ranges, for example 'addA'. Unique across the registry. */
  key: string;
  label: string;
  default: Range;
  /** Smallest allowed lower bound. */
  floor: number;
}

export interface ParamShape {
  ranges: readonly RangeSpec[];
}

export interface Operation {
  id: string;
  label: string;
  symbol: string;
  render(operands: readonly number[]): string;
  paramShape: ParamShape;
  /** Set when this operation is generated by inverting another one. */
  derivesFrom?: string;
  generate(params: GeneratorParams, rng: Rng): Problem;
  sizeMetric(problem: Problem): number;
}
